//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipNetgame_QAAuto {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VipNetgame_QAAuto.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4111111111111111.
        /// </summary>
        internal static string CreditCardVisa {
            get {
                return ResourceManager.GetString("CreditCardVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to djust_test@mail.ru.
        /// </summary>
        internal static string FacebookLogin {
            get {
                return ResourceManager.GetString("FacebookLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 121212qwerty.
        /// </summary>
        internal static string FacebookPass {
            get {
                return ResourceManager.GetString("FacebookPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to djust.test@gmail.com.
        /// </summary>
        internal static string GoogleLogin {
            get {
                return ResourceManager.GetString("GoogleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 121212@qwerty.
        /// </summary>
        internal static string GooglePass {
            get {
                return ResourceManager.GetString("GooglePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to djust_test2@mail.ru.
        /// </summary>
        internal static string InputLogin {
            get {
                return ResourceManager.GetString("InputLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to djust_test1@mail.ru.
        /// </summary>
        internal static string InputLoginfail {
            get {
                return ResourceManager.GetString("InputLoginfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 506452401.
        /// </summary>
        internal static string InputNumber {
            get {
                return ResourceManager.GetString("InputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0637777777.
        /// </summary>
        internal static string InputNumberFail {
            get {
                return ResourceManager.GetString("InputNumberFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 121212qwerty.
        /// </summary>
        internal static string InputPassword {
            get {
                return ResourceManager.GetString("InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 121212qwerty.
        /// </summary>
        internal static string InputPasswordNumber {
            get {
                return ResourceManager.GetString("InputPasswordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to djust_test@mail.ru.
        /// </summary>
        internal static string MailRuLogin {
            get {
                return ResourceManager.GetString("MailRuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 121212qwerty.
        /// </summary>
        internal static string MailRuPass {
            get {
                return ResourceManager.GetString("MailRuPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://stage.vipnetgame.com/.
        /// </summary>
        internal static string MainPageURL {
            get {
                return ResourceManager.GetString("MainPageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fire.
        /// </summary>
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +380506452401.
        /// </summary>
        internal static string OkLogin {
            get {
                return ResourceManager.GetString("OkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 121212qwerty.
        /// </summary>
        internal static string OkPass {
            get {
                return ResourceManager.GetString("OkPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 999.
        /// </summary>
        internal static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to djust_test@mail.ru.
        /// </summary>
        internal static string TwitterLogin {
            get {
                return ResourceManager.GetString("TwitterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 121212qwerty.
        /// </summary>
        internal static string TwitterPass {
            get {
                return ResourceManager.GetString("TwitterPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +380506452401.
        /// </summary>
        internal static string VkLogin {
            get {
                return ResourceManager.GetString("VkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 121212qwerty.
        /// </summary>
        internal static string VkPass {
            get {
                return ResourceManager.GetString("VkPass", resourceCulture);
            }
        }
    }
}
